Feature: event fallthrough for keydown and click
d-i-t-a/R2D2BC pull request #681
Opened 2023-11-27 06:38 UTC by gotson

This PR addresses #627

As mentioned in [my last comment](https://github.com/d-i-t-a/R2D2BC/issues/627#issuecomment-1820555473) on the above issue, event bubbling from an iframe to the container does not work in Javascript, thus injectables do not solve the problem at hand.

Since the `IFrameNavigator` is handling the iframes themselves, and can be configured by the upper component, it makes sense that it allows for event redirection.

The `clickThrough` functions were already there, but not exposed. I added a new API field for this, and i had to change a few things to correctly handle the popup clicks, so that the events are not sent in the `clickThrough` API if they already had an effect in the iFrame. For instance when clicking to reduce the image/footnote popup, the click event will not be falling through.

I implemented something similar for keyboard events, where any keydown event that was not being handled in the Navigator will be falling through to the containing component.

IMHO this is an elegant solution, which allows for out of the box customization without having to resort to injectables.

2024-01-31 03:52 UTC, aferditamuriqi commented on src/modules/search/Popup.ts
> +        win.addEventListener(
I am not seeing anywhere where this event listener is removed.

2024-01-31 03:53 UTC, aferditamuriqi commented
@gotson i will run this locally to better understand and test the PR

2024-02-17 02:58 UTC, aferditamuriqi approved these changes
LGTM

2024-02-17 02:59 UTC, aferditamuriqi commented
@gotson can you please resolve the conflict and also make sure linter is run , thank you , i'll merge it once you have an updated PR

2024-02-17 03:00 UTC, aferditamuriqi requested changes
please resolve conflict

2024-02-19 03:46 UTC, gotson commented
will have a look when time allows

2024-02-20 03:13 UTC, gotson commented
@aferditamuriqi rebased and linted 👍🏻

2024-02-20 15:54 UTC, aferditamuriqi approved these changes

2024-02-20 15:54 UTC, merged